### ISSUE TITLE
 wp-graphql-gravity-forms query names changed?

### ISSUE THREAD

**Issue by IlirBajrami** [kellenmace/headless-wordpress-with-gravity-forms#2]
Did the wp-graphql-gravity-forms query names changed since this repo was created?
I think `gravityFormsForm` query is now called `gfForm` etc...
Is this right or i am missing something?

Even though i updated some queries i again get `Error serializing `.form` returned from `getStaticProps` in "/contact".`.
Maybe the queries are not right.

Also i think there's no `formId` query in the fields fragments.

**Comment by kellenmace** [comment]
Yes, you're correct– since I created this repo, it looks like the maintainer of WPGraphQL for Gravity Forms has renamed the fields. Check out the project's documentation here for the new field names: https://github.com/harness-software/wp-graphql-gravity-forms/tree/develop/docs
